### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dpryan79** [BBCG/epialleleR#1]
During the rollout of Bioconductor 3.16 in Bioconda, I've come across the following error on Linux (but not OSX with clang) in epialleleR:

```
 x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"$PREFIX/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'$PREFIX/lib/R/library/Rcpp/include' -I'$PREFIX/lib/R/library/BH/include' -I'$PREFIX/lib/R/library/Rhtslib/include' -I'$PREFIX/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1667676773505/work=/usr/local/src/conda/r-base-4.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -c rcpp_extract_patterns.cpp -o rcpp_extract_patterns.o
 rcpp_extract_patterns.cpp: In function 'Rcpp::DataFrame rcpp_extract_patterns(Rcpp::DataFrame&, unsigned int, unsigned int, unsigned int, int, std::string&, double, bool, unsigned int, Rcpp::IntegerVector&)':
 rcpp_extract_patterns.cpp:182:39: error: expected ')' before 'PRIX64'
   182 |           snprintf(fnv_str, 17, "%.16" PRIX64, fnv);
       |                   ~                   ^~~~~~~
       |
```

Not being a C++ person (more of a C one), I patched the source to ensure cinttypes was being imported, but that also didn't help. The compiler in this case is GCC 10.4.0. It seems as though the macro isn't getting expanded.

**Comment by oleksii-nikolaienko** [comment]
Thanks for reporting this. Strangely, I didn't receive any notification about this issue and therefore didn't notice it earlier.
It seems that the issue is specific to Bioconda, as it doesn't appear elsewhere? Package is tested on several Linux distributions, Intel and ARM64 OS X, and even Windows, and as long as there is a support for C++17 it should compile... Does the problem persist?

**Comment by oleksii-nikolaienko** [comment]
This was likely an issue until https://github.com/BBCG/epialleleR/issues/8
Now hopefully resolved
