### ISSUE TITLE
  Looks like seqlevels styles of BAM and VCF don't match

### ISSUE THREAD

**Issue by feihongloveworld** [BBCG/epialleleR#10]
Checking BAM file: paired-end, name-sorted alignment detected
Reading paired-end BAM file [0.190s]
Preparing cytosine report [0.112s]
Reading BED file [0.011s]
Reading VCF file [0.426s]
Checking BAM file: paired-end, name-sorted alignment detected
Reading paired-end BAM file [0.195s]
Thresholding reads [0.013s]
Extracting base frequences Error in .getBaseFreqReport(bam.processed = bam, pass = pass, vcf = vcf,  : 
  Looks like seqlevels styles of BAM and VCF don't match. Please provide VCF as an object with correct seqlevels.
Calls: generateVcfReport -> .getBaseFreqReport
Execution halted

**Comment by feihongloveworld** [comment]
sometimes ok， sometime error

**Comment by oleksii-nikolaienko** [comment]
I guess for the same input it should be consistent: either report or error?..
Have a look at the example [here](https://bbcg.github.io/epialleleR/articles/epialleleR.html#exploring-sequence-variants-in-epialleles). You can specify seqlevels of VCF file if it doesn't match seqlevels in BAM.

**Comment by oleksii-nikolaienko** [comment]
Reopen if need any assistance
