### ISSUE TITLE
what's mean of VEF in result file

### ISSUE THREAD

**Issue by feihongloveworld** [BBCG/epialleleR#15]
VEF is the hypermethylation fragment  frequency? or the mean of methylation level of CpGs on hypermethylation fragment VS all CpGs?

**Comment by oleksii-nikolaienko** [comment]
What file are you asking about?
Not sure I understand your question, but if I do - VEF is a frequency of hypermethylated reads, not an average beta value of a read.
I wonder if introduction [here](https://bbcg.github.io/epialleleR/articles/epialleleR.html) or our [publication](https://doi.org/10.1093/gigascience/giad087) would answer it?
