### ISSUE TITLE
Reading BAM fileError: BAM seems to be predominantly single-end or not sorted by QNAME. Single-end alignments are not supported yet. If paired-end, please sort using 'samtools sort -n -o out.bam in.bam

### ISSUE THREAD

**Issue by feihongloveworld** [BBCG/epialleleR#16]
Error Message：Reading BAM fileError: BAM seems to be predominantly single-end or not sorted by QNAME. Single-end alignments are not supported yet. If paired-end, please sort using 'samtools sort -n -o out.bam in.bam'  when there are only several reads in bam。

![image](https://github.com/BBCG/epialleleR/assets/30719145/96adcbbb-4810-4254-898d-061266525cc6)

this error only on linux but not on windows.

I just want that pipeline could run fluency no matter how many reads in bam.

**Comment by oleksii-nikolaienko** [comment]
What version are you running? Try to update to the latest (1.10+), it should read everything

**Comment by oleksii-nikolaienko** [comment]
Guys on a conda side have not prepared that update yet, you'll have to use Bioconductor or pull from github

**Comment by feihongloveworld** [comment]
> What version are you running? Try to update to the latest (1.10+), it should read everything
![image](https://github.com/BBCG/epialleleR/assets/30719145/8430d522-51bd-4c26-9085-d7597940ce72)

will this version of epialleleR raises any error when zero reads in a bam？

**Comment by oleksii-nikolaienko** [comment]
Yes, you need 1.10+ for few reads or single-end. But it won't like 0 reads either, as far as I remember
