### ISSUE TITLE
Truncated bam output when using callMethylation with bwa-meth bam input

### ISSUE THREAD

**Issue by vanreality** [BBCG/epialleleR#29]
Hello @oleksii-nikolaienko,

Great work! I'm currently employing epialleleR to append the XM tag to BAM files generated by BWA-Meth. However, I encountered an issue with corrupted BAM output. This problem persisted even when I attempted to process the test BAM file `bwameth-pe-unsort-yc.bam`, resulting in the same error messages:
      
> @HD     VN:1.6  SO:coordinate
> @SQ     SN:ChrA LN:4900
> @SQ     SN:ChrB LN:4900
> @SQ     SN:ChrC LN:4900
> @RG     ID:SIM  SM:SIM
> @PG     ID:bwa-meth     PN:bwa-meth     VN:0.2.6        CL:"/usr/local/tools/_conda/envs/__bwameth@0.2.6/bin/bwameth.py -t 8 --reference index_dir/genome.fa --read-group SIM input_f.fastq input_r.fastq"
> @PG     ID:samtools     PN:samtools     PP:bwa-meth     VN:1.18 CL:/tools/samtools_1.18/bin/samtools view -h bwameth.addXM.bam
> [E::sam_format1_append] Corrupted aux data for read 35_ChrA:126-198
> samtools view: writing to standard output failed: Invalid argument
> samtools view: error reading file "bwameth.addXM.bam": Invalid argument

epialleleR : v1.10.0
samtools : v1.18

**Comment by oleksii-nikolaienko** [comment]
Hi and thanks for using and reporting this :)
Not able to check atm due to traveling, but are you able to reproduce this with the latest developmental version (1.11.9)?

**Comment by vanreality** [comment]
An error occurred while I created a pure R4.3 singularity container to install 1.11.9 using `remotes::install_github("BBCG/epialleleR")` :
<img width="1723" alt="image" src="https://github.com/BBCG/epialleleR/assets/26620356/c94bf434-a14e-427f-9870-c5b839a1e6be">
I reinstalled Rhtslib but unfortunately still not working

**Comment by oleksii-nikolaienko** [comment]
I see. The 1.11.9 version of epialleleR (as well as future release 1.12) requires [dev Rhtslib v2.99](https://bioconductor.org/packages/devel/bioc/html/Rhtslib.html). You can install this updated Rhtslib as a standalone package and this will allow to build epialleleR.
As for initial error, I can reproduce it for epialleleR v1.10, but not for v1.11, so updating to v1.11 or future release v1.12 will solve it for you

**Comment by oleksii-nikolaienko** [comment]
As a sidenote, v1.11.9 is also much better tested for methylation calling. But please report if you see something unexpected or significant discrepancies between epialleleR and other callers.

**Comment by vanreality** [comment]
Thanks a lot for your instructions!

I successfully tested epialleleR v1.11.9 on a WGBS sample and compared XM tag similarity assigned by epialleleR and bismark. The results showed that 98.61% of reads in the BWAmeth BAM achieved 100% XM tag similarity to the reads of Bismark BAM.

From previous experiences, BWAmeth typically surpasses other aligners in mapping rate, accuracy, and efficiency. Notably, its use in Nvidia's Parabricks for GPU acceleration underscores its potential. However, a notable gap exists in tools for extracting read-level methylation data from BWAmeth BAM files. The introduction of epialleleR is thus a timely and exciting development.

**Comment by oleksii-nikolaienko** [comment]
Thanks for thorough testing! I try to check things as rigorously as possible, but there can always be something that isn't right. It's always good to hear that stuff is quality assured by others in real tasks.
My data is produced exclusively by Illumina sequencers and aligned on DRAGEN. I guess, it has some modification of BWA, and we are also pretty happy with the mapping quality.
