### ISSUE TITLE
install failed ！！

### ISSUE THREAD

**Issue by feihongloveworld** [BBCG/epialleleR#8]
install_github("BBCG/epialleleR", build_vignettes=FALSE,
repos=BiocManager::repositories(),
dependencies=TRUE, type="source")
Downloading GitHub repo BBCG/epialleleR@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ checking for file ‘/tmp/RtmpPln2BE/remotes58aef7928d92a/BBCG-epialleleR-9a49d74/DESCRIPTION’ (425ms)
─ preparing ‘epialleleR’:
✔ checking DESCRIPTION meta-information ...
─ cleaning src
─ checking for LF line-endings in source and make files and shell scripts
─ checking for empty or unneeded directories
─ building ‘epialleleR_1.9.5.tar.gz’

installing source package ‘epialleleR’ ...
** using staged installation
** libs
using C++ compiler: ‘x86_64-conda-linux-gnu-c++ (conda-forge gcc 13.1.0-0) 13.1.0’
using C++17
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib -fpic -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix -c RcppExports.cpp -o RcppExports.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib -fpic -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix -c rcpp_call_methylation.cpp -o rcpp_call_methylation.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib -fpic -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix -c rcpp_check_bam.cpp -o rcpp_check_bam.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib -fpic -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix -c rcpp_cx_report.cpp -o rcpp_cx_report.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib -fpic -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix -c rcpp_extract_patterns.cpp -o rcpp_extract_patterns.o
rcpp_extract_patterns.cpp: In function 'Rcpp::DataFrame rcpp_extract_patterns(Rcpp::DataFrame&, unsigned int, unsigned int, unsigned int, int, std::string&, double, bool, unsigned int, Rcpp::IntegerVector&)':
rcpp_extract_patterns.cpp:176:39: error: expected ')' before 'PRIX64'
176 | snprintf(fnv_str, 17, "%.16" PRIX64, fnv);
| ~ ^~~~~~~
| )
rcpp_extract_patterns.cpp:4:1: note: 'PRIX64' is defined in header ''; did you forget to '#include '?
3 | #include "epialleleR.h"
+++ |+#include
4 | // using namespace Rcpp;
make: *** [/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/etc/Makeconf:200: rcpp_extract_patterns.o] Error 1
ERROR: compilation failed for package ‘epialleleR’
removing ‘/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/epialleleR’
Warning message:
In i.p(...) :
installation of package ‘/tmp/RtmpPln2BE/file58aef339fa842/epialleleR_1.9.5.tar.gz’ had non-zero exit status

**Comment by oleksii-nikolaienko** [comment]
Thanks for reporting.
This has happened once in the context of conda environment. For some reason conda-provided GCC fails to recognise PRIX64 macros. Don't know if it's my fault, but I never get such issue on any of platforms. Can you build it using other, non-conda compiler?
I suppose BiocManager::install("epialleleR") fails as well?

**Comment by feihongloveworld** [comment]
I'm not a root user, so I prefer to use conda to install those soft which I want.  i don't want to waste time on dealling with complex dependence.
The "epiallelR" can be installed successfully on Windows 11. 
Maybe you can make a docker container of “epiallelR” for different platforms。

**Comment by oleksii-nikolaienko** [comment]
I made a small change. Could you try `install_github` again?

**Comment by feihongloveworld** [comment]
should I try it on linux?

**Comment by feihongloveworld** [comment]
> I made a small change. Could you try `install_github` again?

library(devtools)
Loading required package: usethis
> install_github("BBCG/epialleleR", build_vignettes=FALSE,
  repos=BiocManager::repositories(),
  dependencies=TRUE, type="source")
Downloading GitHub repo BBCG/epialleleR@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                
2: CRAN packages only                 
3: None                               
4: fontawesome (0.5.1 -> 0.5.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
fontawesome (0.5.1 -> 0.5.2) [CRAN]
Installing 1 packages: fontawesome
trying URL 'https://cloud.r-project.org/src/contrib/fontawesome_0.5.2.tar.gz'
Content type 'application/x-gzip' length 1281884 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

* installing *source* package ‘fontawesome’ ...
** package ‘fontawesome’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (fontawesome)

The downloaded source packages are in
        ‘/tmp/RtmpVJxoq7/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpVJxoq7/remotes2334e49ab852f/BBCG-epialleleR-86ebe4a/DESCRIPTION’ (430ms)
─  preparing ‘epialleleR’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘epialleleR_1.9.5.tar.gz’
   
* installing *source* package ‘epialleleR’ ...
** using staged installation
** libs
using C++ compiler: ‘x86_64-conda-linux-gnu-c++ (conda-forge gcc 13.1.0-0) 13.1.0’
using C++17
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix  -c rcpp_call_methylation.cpp -o rcpp_call_methylation.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix  -c rcpp_check_bam.cpp -o rcpp_check_bam.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix  -c rcpp_cx_report.cpp -o rcpp_cx_report.o
x86_64-conda-linux-gnu-c++ -std=gnu++17 -I"/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rcpp/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/BH/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/Rhtslib/include' -I'/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -I/share/sygene16/mambaforge/envs/Fragment_Level/include -Wl,-rpath-link,/share/sygene16/mambaforge/envs/Fragment_Level/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /share/sygene16/mambaforge/envs/Fragment_Level/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1689933267587/work=/usr/local/src/conda/r-base-4.3.1 -fdebug-prefix-map=/share/sygene16/mambaforge/envs/Fragment_Level=/usr/local/src/conda-prefix  -c rcpp_extract_patterns.cpp -o rcpp_extract_patterns.o
rcpp_extract_patterns.cpp: In function 'Rcpp::DataFrame rcpp_extract_patterns(Rcpp::DataFrame&, unsigned int, unsigned int, unsigned int, int, std::string&, double, bool, unsigned int, Rcpp::IntegerVector&)':
rcpp_extract_patterns.cpp:177:39: error: expected ')' before 'PRIX64'
  177 |           snprintf(fnv_str, 17, "%.16" PRIX64, fnv);
      |                   ~                   ^~~~~~~
      |                                       )
rcpp_extract_patterns.cpp:5:1: note: 'PRIX64' is defined in header '<cinttypes>'; did you forget to '#include <cinttypes>'?
    4 | #include "epialleleR.h"
  +++ |+#include <cinttypes>
    5 | // using namespace Rcpp;
make: *** [/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/etc/Makeconf:200: rcpp_extract_patterns.o] Error 1
ERROR: compilation failed for package ‘epialleleR’
* removing ‘/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/epialleleR’
* restoring previous ‘/share/sygene16/mambaforge/envs/Fragment_Level/lib/R/library/epialleleR’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpVJxoq7/file2334e55e7b2aa/epialleleR_1.9.5.tar.gz’ had non-zero exit status

**Comment by oleksii-nikolaienko** [comment]
Please try once again

**Comment by feihongloveworld** [comment]
installed successfully, I will check if it running properly. 
thank you for your job.

**Comment by oleksii-nikolaienko** [comment]
thank you too. I don't use conda myself and when package passes all Bioc tests I wrongly assume that there will be no compilation issues

**Comment by oleksii-nikolaienko** [comment]
resolved by https://github.com/BBCG/epialleleR/commit/f7f71c2ec60651bdd14f2af2bfb29bf2fae3ae9d
