### ISSUE TITLE
Preparing amplicon report Error 

### ISSUE THREAD

**Issue by feihongloveworld** [BBCG/epialleleR#9]
Attaching package: ‘ggstance’

The following objects are masked from ‘package:ggplot2’:

    geom_errorbarh, GeomErrorbarh

Reading BED file [0.098s]
Checking BAM file: paired-end, name-sorted alignment detected
Reading paired-end BAM file [0.053s]
Thresholding reads [0.001s]
Preparing amplicon report Error in set(i, j = ic, value = chmatch(levels(i[[ic]]), levels(x[[xc]]),  : 
  RHS of assignment to existing column 'strand' is zero length but not NULL. If you intend to delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_. If you are trying to change the column type to be an empty list column then, as with all column type changes, provide a full length RHS vector such as vector('list',nrow(DT)); i.e., 'plonk' in the new column.
Calls: generateAmpliconReport ... dcast.data.table -> [ -> [.data.table -> bmerge -> set
Execution halted

**Comment by feihongloveworld** [comment]
Bam information:
![image](https://github.com/BBCG/epialleleR/assets/30719145/8f84a1a5-dc90-4948-b0d3-083824cdffbd)
Bed information:
![image](https://github.com/BBCG/epialleleR/assets/30719145/dd342b71-7782-4679-af62-2e107c737c60)

**Comment by feihongloveworld** [comment]
Firstly, there are only 3 paired reads in the sample bam. Is it because reads count is too small?
secondly, is there strand parameter in the generateAmpliconReport function just for a specific stand information?

**Comment by oleksii-nikolaienko** [comment]
Any chance to get (some of) this BAM to investigate?
Is it an amplicon-seq?

**Comment by oleksii-nikolaienko** [comment]
There's no specific parameter, but you will see number of reads for each of strands separately

**Comment by oleksii-nikolaienko** [comment]
Hi @feihongloveworld, are you still having this issue? Anything I could help you with here?

**Comment by oleksii-nikolaienko** [comment]
Reopen if need any assistance
